<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>CodePath.Modules.Auth.Api</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CodePath.Modules.Auth.Application\CodePath.Modules.Auth.Application.csproj" />
    <ProjectReference Include="..\CodePath.Modules.Auth.Infrastructure\CodePath.Modules.Auth.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\Shared\CodePath.Shared.Web\CodePath.Shared.Web.csproj" />
  </ItemGroup>
</Project>
