<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <RootNamespace>CodePath.Architecture.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Domain\CodePath.Domain\CodePath.Domain.csproj" />
    <ProjectReference Include="..\..\src\Application\CodePath.Application\CodePath.Application.csproj" />
    <ProjectReference Include="..\..\src\Infrastructure\CodePath.Infrastructure\CodePath.Infrastructure.csproj" />
  </ItemGroup>
</Project>
